basePath: /
definitions:
  model.AttendanceRecord:
    properties:
      id:
        type: integer
      student_id:
        type: integer
      subject_id:
        type: integer
      visit_day:
        type: string
      visited:
        type: boolean
    type: object
  model.AuthRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.CreateStudentRequest:
    properties:
      birth_date:
        type: string
      first_name:
        type: string
      firstname:
        description: frontend alias
        type: string
      gender:
        type: string
      group_id:
        type: integer
      group_name:
        type: string
      last_name:
        type: string
      surname:
        description: frontend alias
        type: string
    type: object
  model.LoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/model.User'
    type: object
  model.ScheduleResponse:
    properties:
      class_time:
        type: string
      faculty:
        type: string
      group:
        type: string
      id:
        type: integer
      subject:
        type: string
    type: object
  model.StudentListResponse:
    properties:
      email:
        type: string
      first_name:
        type: string
      group:
        type: string
      id:
        type: integer
      last_name:
        type: string
    type: object
  model.StudentResponse:
    properties:
      birth_date:
        type: string
      first_name:
        type: string
      gender:
        type: string
      group_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
    type: object
  model.UpdateStudentRequest:
    properties:
      birth_date:
        type: string
      first_name:
        type: string
      firstname:
        type: string
      gender:
        type: string
      group_id:
        type: integer
      group_name:
        type: string
      last_name:
        type: string
      surname:
        type: string
    type: object
  model.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
    type: object
host: uni-server-29pn.onrender.com
info:
  contact: {}
  description: University management API - students, schedules, attendance
  title: University API
  version: "1.0"
paths:
  /all_class_schedule:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ScheduleResponse'
            type: array
      summary: Get all schedules
      tags:
      - schedules
  /api/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.AuthRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResponse'
      summary: Login
      tags:
      - auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.AuthRequest'
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
      summary: Register a new user
      tags:
      - auth
  /attendance:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.AttendanceRecord'
            type: array
      summary: Get all attendance records
      tags:
      - attendance
    post:
      consumes:
      - application/json
      parameters:
      - description: Attendance data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.AttendanceRecord'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.AttendanceRecord'
      summary: Create attendance record
      tags:
      - attendance
  /student/{id}:
    get:
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.StudentResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get student by ID
      tags:
      - students
  /students:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.StudentListResponse'
            type: array
      summary: Get all students
      tags:
      - students
    post:
      consumes:
      - application/json
      parameters:
      - description: Student data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.CreateStudentRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.StudentResponse'
      summary: Create a student
      tags:
      - students
  /students/{id}:
    delete:
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      summary: Delete a student
      tags:
      - students
    patch:
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: string
      - description: Update data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.UpdateStudentRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.StudentResponse'
      summary: Update a student
      tags:
      - students
schemes:
- https
swagger: "2.0"
